/* SISTAFUND — shared data (portfolio companies + community LPs)
   Loaded by index.html, portfolio.html and community.html. */

window.COMPANIES = {
  pave: ['Pave Space', 'Frontier Tech', 'pave.png', 'Heavy kickstage to unlock orbital logistics.', 'Julie Böhning, Jérémy Marciacq', 'Vaud (CH), 2023'],
  waiv: ['Waiv', 'HealthTech', 'waiv.png', 'Accelerating AI-enabled precision oncology testing.', 'Meriem Sefta, Lionel Guillou', 'Paris, 2025'],
  recupere: ['Recupere Metals', 'Sustainability', 'recupere.png', 'Patented mechanical process producing electrical-grade copper wire from 100% recycled scrap.', 'Katie Marsh, Julien Vaïssette', 'Paris, 2025'],
  tec: ['The Exploration Company', 'Frontier Tech', 'tec.png', 'Democratizing space exploration, making it affordable, sustainable and open, for space & non-space industries.', 'Hélène Huby & co-founders', 'Bordeaux, 2021'],
  numi: ['Nūmi', 'HealthTech', 'numi.jpg', 'Developing in vivo breast milk, in vitro.', 'Eden Banon-Lagrange, Eugénie Pezé-Heidsieck', 'Paris, 2023'],
  orakl: ['Orakl Oncology', 'HealthTech', 'orakl.png', 'Accelerating drug discovery in oncology.', 'Fanny Jaulin, Diane-Laure Pagès, Gustave Ronteix', 'Paris, 2023'],
  femaleinvest: ['Female Invest', 'Fintech', 'femaleinvest.webp', 'On a mission to close the financial gender gap, democratizing investing for everyone, globally.', 'A.-S. Hartvigsen, C. Falkenberg, E. Due Bitz', 'Copenhagen, 2021'],
  underdog: ['Underdog', 'Sustainability', 'underdog.png', 'Full-stack solution for refurbished household appliances, structuring the circular economy in Europe.', 'Claire Bretton, Laura Chavigny, Mathieu Maure', 'Nantes / Paris, 2022'],
  astran: ['Astran', 'Frontier Tech', 'astran.png', 'Zero Trust cloud storage solution for sensitive data.', 'Yosra Jarraya, Gilles Seghaier, Yahya Jarraya', 'Paris, 2021'],
  mallow: ['Mallow', 'Frontier Tech', 'mallow.png', 'Educational toys for children at the intersection of cognitive science and AI.', 'Flore Cousin, Cédric O', 'Paris, 2024'],
  vizzia: ['Vizzia', 'Sustainability', 'vizzia.png', 'Leveraging computer vision and AI to detect illegal waste dumping.', 'Katrin de Proyart, Alexandre Leboucher', 'Paris, 2022'],
  optimiz: ['Optimiz Construction', 'Sustainability', 'optimiz.png', 'Helping construction firms optimize materials to save time, money and CO₂.', 'Marion Malandain', 'Paris, 2020'],
  notom: ['NOTOM', 'Frontier Tech', 'notom.png', 'Bridging OT & IT through AI-driven reindustrialisation in factories.', 'Paola Fedou, Jean-Philippe Gross', 'Paris, 2025'],
  stealth: ['Stealth', 'Frontier Tech', 'stealth.png', 'Unlocking Ocean Intelligence.', '', 'UK, 2022'],
  stealth2: ['Stealth', 'HealthTech', 'stealth2.png', 'Gut Health Monitoring.', '', 'UK, 2026'],
};

window.LPS = [
  ['Steve Anavi', 'Qonto', 'steve-anavi.jpg', 'fintech'],
  ['Rémi Aubert', 'AB Tasty', 'remi-aubert.png', 'saas'],
  ['Nathalie Balla', 'La Redoute', 'nathalie-balla.jpg', 'consumer'],
  ['Jonathan Benhamou', 'Resilience, PeopleDoc', 'jon-benhamou.jpg', 'health'],
  ['Amélie Berthier', 'Zadig & Voltaire', 'amelie-berthier.jpg', 'consumer'],
  ['Clément Buyse', 'PeopleDoc', 'clement-buyse.jpg', 'saas'],
  ['Nicolas Chartier', 'Aramis Group', 'nicolas-chartier.jpg', 'consumer'],
  ['Michael Chekroun', 'Carenity', 'michael-chekroun.jpg', 'health'],
  ['Valentine de Lasteyrie', 'Albingia, Fiblac', 'valentine-de-lasteyrie.jpg', 'fintech'],
  ['Alix de Sagazan', 'AB Tasty', 'alix-de-sagazan.jpg', 'saas'],
  ['Marine de Waziers', 'Pool', 'marine-de-waziers.png', 'consumer'],
  ['Alice Default', 'Double', 'alice-default.png', 'saas'],
  ['Laurent Delaporte', 'Qapa, Microsoft', 'laurent-delaporte.jpg', 'saas'],
  ['Xavier Durand', 'Aircall', 'xavier-durand.jpg', 'saas'],
  ['Fabien Grenier', 'DataDome', 'fabien-grenier.jpg', 'frontier'],
  ['Jean-Daniel Guyot', 'Memo Bank, Captain Train', 'jd-guyot.jpg', 'fintech'],
  ['Nicolas Hernandez', '360Learning', 'nicolas-hernandez.jpg', 'saas'],
  ['Céline Lazorthes', 'Resilience, Leetchi', 'celine-lazorthes.jpg', 'fintech'],
  ['Constance Nevoret', 'LittleBig Connection', 'constance-nevoret.jpg', 'saas'],
  ['Xavier Niel', 'Free', 'xavier-niel.png', 'frontier'],
  ['Adrien Nussenbaum', 'Mirakl', 'adrien-nussenbaum.jpg', 'saas'],
  ['Philippe Oddo', 'ODDO BHF', 'phillippe-oddo.jpg', 'fintech'],
  ['Stéphane Pallez', 'Française des Jeux', 'stephane-pallez.jpg', 'consumer'],
  ['Nicolas Reboud', 'Shine', 'nicolas-reboud.jpg', 'fintech'],
  ['Cédric Sellin', 'Yogiplay, Oracle', 'cedric-sellin.jpg', 'saas'],
  ['Xavier Zeitoun', 'Zenchef', 'xavier-zeitoun.png', 'saas'],
  ['Frank Zorn', 'Deskeo', 'frank-zorn.jpg', 'consumer'],
];

/* Press & news — [date, source, title, url], newest first */
window.NEWS = [
  ["25/03/2026", "Portfolio", "Redefining the last mile of space: PAVE Space raises $40M!", "https://pave.space/page/homepage"],
  ["12/03/2026", "Portfolio", "Waiv secures $33 million to scale AI precision testing", "https://wearewaiv.com/news/waiv-secures-33-million-to-scale-ai-precision-testing"],
  ["02/02/2026", "Maddyness", "When circular industrial tech meets Europe's strategic autonomy: Recupere Metals raises €5m!", "https://www.maddyness.com/2026/01/30/face-a-une-demande-de-cuivre-qui-explose-recupere-metals-leve-5-millions-deuros/"],
  ["21/01/2026", "Maddyness", "When re-industrialisation meets AI: NOTOM raises €2M!", "https://www.maddyness.com/2026/01/21/des-ex-dinnovafeed-levent-2-millions-deuros-pour-mettre-de-lia-dans-les-usines/"],
  ["14/01/2026", "Scientific Reports", "A major scientific milestone for Nūmi®", "https://www.nature.com/articles/s41598-025-33232-y"],
  ["09/12/2025", "LinkedIn", "Happy birthday SISTA!", "https://www.linkedin.com/feed/update/urn:li:activity:7406631404983250944"],
  ["03/12/2025", "LinkedIn", "Underdog at the Élysée as 40/120 Impact Index laureate", "https://www.linkedin.com/feed/update/urn:li:activity:7401893064530763776"],
  ["15/10/2025", "LinkedIn", "Run & Breakfast with Auxxo, Fund F and Pitch in Motion during unlock VC", "https://www.linkedin.com/feed/update/urn:li:activity:7381227283875004418"],
  ["14/10/2025", "LinkedIn", "100 Women in Tech: Exclusive Dinner!", "https://www.linkedin.com/feed/update/urn:li:activity:7383757707515805696"],
  ["10/10/2025", "Sifted", "100 Women in Tech Europe 2025 by SISTAFUND, Sifted & Station F", "https://sifted.eu/list/100-women-in-tech-2025"],
  ["10/10/2025", "Challenges", "Astran wins the Innovation Award at Monaco's 2025 Cybersecurity Conference", "https://www.challenges.fr/la-verticale-cyber/la-pepite-francaise-astran-qui-permet-aux-entreprises-de-fonctionner-malgre-une-cyberattaque-recompensee-a-monaco_627188"],
  ["08/10/2025", "LinkedIn", "The Exploration Company lit up the Nasdaq Tower in Times Square", "https://www.linkedin.com/feed/update/urn:li:activity:7381580404551680000"],
  ["17/09/2025", "LinkedIn", "Vizzia raised their €16M Series A", "https://www.linkedin.com/feed/update/urn:li:activity:7374009611219001345"],
  ["01/07/2025", "B Smart", "Sanofi and Astran announce a strategic partnership", "https://www.bsmart.fr/video/29295-smart-tech-30-juin-2025"],
  ["19/06/2025", "Philomag", "Does our future depend on technology? Philosophy Baccalaureate 2025", "https://www.philomag.com/articles/corriges-du-bac-philo-filiere-generale-notre-avenir-depend-il-de-la-technique"],
  ["17/06/2025", "LinkedIn", "VivaTech 2025 wrap up", "https://www.linkedin.com/feed/update/urn:li:activity:7340637829795897344"],
  ["04/06/2025", "YouTube", "The backstages of Underdog with Mathieu Maure", "https://www.youtube.com/watch?v=XnhUlaoPuv8"],
  ["02/10/2024", "Ouest France", "Underdog wins the Special Jury Prize for Start-up of the Year in the French West region!", "https://www.ouest-france.fr/economie/prix-ey-de-lentrepreneur-de-lannee-2024-six-entreprises-de-louest-primees-b97eb1be-7a5a-11ef-822e-4d3ac9af3b93"],
  ["27/09/2024", "Alliancy", "Astran completely rethinks data security", "https://www.alliancy.fr/whats-next-cio-astran-repense-integralement-la-securisation-des-donnees"],
  ["11/09/2024", "Cash Confidences", "Tatiana Jama on the Cash Confidences podcast", "https://podcast.ausha.co/cash-confidences/tatiana-jama"],
  ["29/07/2024", "Business Insider", "Female Invest raised their Series A", "https://www.businessinsider.com/fintech-startup-female-invest-raises-equity-plots-us-growth-2024-7"],
  ["17/07/2024", "Les Echos", "Bikini, the capsule of The Exploration Company, made it to space", "https://www.lesechos.fr/start-up/ecosysteme/french-tech-the-exploration-company-va-tester-sa-capsule-miniature-sur-ariane-6-2106613"],
  ["10/07/2024", "Forbes", "Tatiana Jama featured in Forbes' 2024 « 40 Women to Watch » edition!", "https://boutique.forbes.fr/"],
  ["20/06/2024", "European Women in VC", "European Women in VC report 2024: « Beyond Returns »", "https://drive.google.com/file/d/1NIT9fyQn24Fndi4foAw9-lI1oFBGLe-6/view"],
  ["31/05/2024", "European Spaceflight", "Starlab contracts The Exploration Company for 3 cargo missions", "https://europeanspaceflight.com/starlab-contracts-the-exploration-company-for-3-cargo-missions/"],
  ["22/05/2024", "ESA", "ESA signs contracts for commercial space cargo return service", "https://www.esa.int/Science_Exploration/Human_and_Robotic_Exploration/ESA_signs_contracts_for_commercial_space_cargo_return_service"],
  ["17/05/2024", "Le Revenu", "Tatiana Jama: « Diversity in management creates performance »", "https://www.lerevenu.com/les-grands-entretiens/la-diversite-dans-le-management-dune-entreprise-cree-de-la-performance/"],
  ["14/05/2024", "Yahoo Finance", "Hourglass in City highlights 'painfully' slow progress closing the gender investment gap", "https://uk.finance.yahoo.com/news/hourglass-city-highlights-painfully-slow-160704539.html"],
  ["08/05/2024", "Les Glorieuses", "L'argent est-il sexiste?", "https://lesglorieuses.fr/largent-est-il-sexiste/"],
  ["07/05/2024", "Radio Classique", "Tatiana Jama, author of « L'entrepreneuriat, un nouveau féminisme »", "https://podcast.ausha.co/les-voix-de-l-economie/tatiana-jama-auteure-de-l-entrepreneuriat-un-nouveau-feminisme-aux-editions-de-l-observatoire"],
  ["24/04/2024", "Éditions de l'Observatoire", "L'entrepreneuriat, un nouveau féminisme — Tatiana Jama", "https://editions-observatoire.com/livre/L%27entrepreneuriat%2C-un-nouveau-feminisme/529"],
  ["08/04/2024", "Maddyness", "Investing in gender-balanced teams to drive performance: a profile of SISTAFUND", "https://www.maddyness.com/uk/2024/04/08/investing-in-gender-balanced-teams-to-drive-perfromance-a-profile-of-sistafund/"],
  ["22/03/2024", "Astran", "Astran is Europe's most promising cyber security solution", "https://www.astran.io/news/most-promising-cyber-security-solution"],
  ["19/03/2024", "Astran", "Astran selected by the government, ANSSI and Bpifrance for the SecNumCloud acceleration program", "https://www.astran.io/blog/astran-is-now-officially-selected-by-the-government-the-anssi-and-bpifrance-for-the-secnumcloud-acceleration-program"],
  ["08/03/2024", "SISTAFUND", "Opinion: Gender Equality — Towards Truly Gender-Equal Investment", "https://sistafund.com/news/451/"],
  ["07/03/2024", "Challenges", "Underdog builds an industrial refurbishment supply chain", "https://www.challenges.fr/club-entrepreneurs/underdog-developpe-une-filiere-industrielle-du-reconditionnement_885450"],
  ["23/01/2024", "The Standard", "Female Invest co-founder Anna-Sophie Hartvigsen on changing your financial fortunes", "https://www.standard.co.uk/lifestyle/finance-tips-how-to-invest-make-more-money-2024-b1130378.html"],
  ["14/11/2023", "Maddyness", "Isabelle Drault Gallo (SISTAFUND): « I want to show that diversity drives performance »", "https://www.maddyness.com/2023/11/14/isabelle-drault-gallo-sista-fund-je-veux-montrer-que-la-diversite-est-un-gage-de-performance/"],
  ["13/10/2023", "SISTAFUND", "Brunch with SISTAFUND's Tatiana Jama: 'I want to have real impact'", "https://sistafund.com/news/brunch-with-sistafunds-tatiana-jama-i-want-to-have-real-impact/"],
  ["03/10/2023", "SISTAFUND", "Financial literacy as key leverage to women's empowerment", "https://sistafund.com/news/from-the-funding-gap-to-the-financial-gender-gap-financial-literacy-as-key-leverage-to-womens-empowerment/"],
  ["27/09/2023", "Les Echos", "Claire Bretton, taking on large household appliances", "https://www.lesechos.fr/industrie-services/conso-distribution/claire-bretton-a-lassaut-du-gros-electromenager-1981899"],
  ["17/07/2023", "BFM Business", "Vizzia wants to help cities tackle illegal dumping with autonomous cameras", "https://www.bfmtv.com/economie/replay-emissions/tech-and-co/alexandre-leboucher-vizzia-vizzia-veut-aider-les-villes-a-se-debarrasser-des-depots-sauvages-avec-des-cameras-autonomes-17-07_VN-202307170707.html"],
  ["04/07/2023", "SISTAFUND", "Reconciling economic and ecological performance: backing Optimiz Construction!", "https://sistafund.com/news/helping-construction-companies-reconcile-economic-and-ecological-performance-backing-optimiz-construction/"],
  ["12/06/2023", "SISTAFUND", "Ensuring data security while upholding digital sovereignty: backing Astran!", "https://sistafund.com/news/ensuring-data-security-while-upholding-digital-sovereignty-backing-astran/"],
  ["31/05/2023", "SISTAFUND", "Unleashing the power of AI to make the world cleaner: backing Vizzia!", "https://sistafund.com/news/backing-the-cleantech-vizzia/"],
  ["30/05/2023", "Les Echos", "Vizzia, the start-up that wants to end street waste in cities", "https://www.lesechos.fr/start-up/deals/vizzia-la-start-up-qui-veut-mettre-fin-aux-dechets-dans-les-rues-des-villes-1947448"],
  ["04/04/2023", "SISTAFUND", "Making second life the first choice: backing Underdog", "https://sistafund.com/news/making-second-life-the-first-choice-backing-underdog/"],
  ["01/02/2023", "tech.eu", "SISTAFUND's first investment: The Exploration Company lands €40.5 million", "https://tech.eu/2023/02/01/in-no-way-boring-spacetech-startup-the-exploration-company-lands-eur405-million/"],
  ["18/11/2022", "BFM TV", "BFM with Fred Mazzella: trading the lawyer's robe for entrepreneurship", "https://www.bfmtv.com/economie/replay-emissions/les-pionniers-chez-fred-mazzella/tete-a-tete-troquer-la-robe-d-avocat-pour-l-entrepreneuriat-18-11_VN-202211180828.html"],
  ["07/11/2022", "Maddyness", "Maddyness: the profile of SISTAFUND", "https://www.maddyness.com/2022/11/07/que-font-les-fonds-sistafund/"],
  ["24/10/2022", "Décideurs Magazine", "« Women entrepreneurs are underfunded in the world of venture capital »", "https://www.decideurs-magazine.com/finance/53239-t-jama-sista-les-femmes-entrepreneures-sont-sous-financees-dans-le-monde-du-venture-capital.html"],
  ["17/10/2022", "Informelles", "What is SISTAFUND, announced by SISTA and 50Partners?", "https://www.informelles.media/money-news-sista-annonce-son-premier-fonds-dinvestissement/"],
  ["14/10/2022", "Private Equity Magazine", "SISTAFUND seeds mixed and female entrepreneurship", "https://www.pemagazine.fr/NzY5NA/sistafund-amorce-lentrepreneuriat-mixte-ou-feminin"],
  ["13/10/2022", "Madame Figaro", "« In the coming years, several unicorns will be led by women and we will finance them »", "https://madame.lefigaro.fr/business/actu-business/tatiana-jama-du-collectif-sista-dans-les-prochaines-annees-plusieurs-licornes-seront-dirigees-par-des-femmes-et-nous-allons-les-financer-20221013"],
  ["11/10/2022", "Fashion Network", "SISTA to finance female entrepreneurship with a €100 million fund", "https://fr.fashionnetwork.com/news/Sista-veut-financer-l-entrepreneuriat-feminin-en-creant-son-fonds-de-100-millions-d-euros,1445777.html"],
  ["04/10/2022", "Les Echos Capital Finance", "SISTA launches a €100M fund for start-ups founded by women", "https://capitalfinance.lesechos.fr/fonds/levees/sista-lance-un-fonds-de-100-m-pour-les-start-up-creees-par-des-femmes-1866316"],
  ["04/10/2022", "Les Echos", "The SISTA collective launches a fund to finance women entrepreneurs", "https://www.lesechos.fr/start-up/deals/le-collectif-sista-lance-un-fonds-pour-financer-les-femmes-entrepreneures-1865779"],
  ["04/10/2022", "Sifted", "France's SISTA announces first close of €100m VC fund", "https://sifted.eu/articles/sista-vc-fund-raise-france/"],
  ["24/03/2022", "SISTAFUND", "SISTA x Mirova Forward study: what if we asked women and men the same questions?", "https://sistafund.com/news/et-si-on-posait-les-memes-questions-aux-femmes-et-aux-hommes-etude-sista-x-mirova-forward/"],
];

/* per-article thumbnails pulled from sistafund.com/news, same order as NEWS */
window.NEWS_IMG = ["n01.webp", "n02.jpg", "n03.jpg", "n04.jpg", "n05.jpeg", "n06.jpeg", "n07.jpeg", "n08.jpeg", "n09.jpeg", "n10.jpeg", "n11.jpeg", "n12.jpeg", "n13.jpeg", "n14.jpeg", "n15.jpeg", "n16.jpeg", "n17.jpeg", "n18.png", "n19.jpg", "n20.jpeg", "n21.jpg", "n22.webp", "n23.jpeg", "n24.png", "n25.jpeg", "n26.jpg", "n27.png", "n28.jpeg", "n29.png", "n30.png", "n31.png", "n32.webp", "n33.jpg", "n34.jpeg", "n35.webp", "n36.jpg", "n37.png", "n38.webp", "n39.png", "n40.webp", "n41.webp", "n42.png", "n43.jpeg", "n44.jpg", "n45.webp", "n46.webp", "n47.png", "n48.webp", "n49.png", "n50.jpg", "n51.png", "n52.jpg", "n53.jpg", "n54.png", "n55.png", "n56.webp", "n57.jpg", "n58.jpg", "n59.png"];
